---

- name: Installing Remi Repository
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Install PHP with necessary extensions
  yum:
    enablerepo: "remi,remi-php81"
    name:
      - php
      - php-curl
      - php-gd
      - php-cli
      - php-mysql
      - php-xml
      - php-mbstring
      - php-fpm
      - php-intl
      - php-zip
      - php-xsl
    state: latest

- name: Start and enable service
  service: name=php-fpm state=started enabled=yes

- name: Fix permissions
  file:
    path: "/var/run/php-fpm/"
    owner: wilfred
    mode: 0777
    state: directory
    recurse: yes

#- name: Generate a new configuration for PHP-FPM
#  template:
#    src: www.conf
#    dest: /etc/php-fpm.d/www.conf
#    owner: wilfred

- name: Restart php-fpm
  service: name=php-fpm state=restarted
