---
- name: Composer install
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer warn=False
  args:
    creates: /usr/local/bin/composer

- name: GIT Install
  package: name=git state=latest

- name: Clone Drush repository
  git:
    repo: https://github.com/drush-ops/drush.git
    version: "12.1.2"
    dest: /opt/drush

- name: Install Mysql Repo
  yum:
    name: http://repo.mysql.com/mysql57-community-release-el7-10.noarch.rpm
    state: present

- name: Enable and install mysql
  yum:
    name:
      - mysql-community-server
    state: present

- name: Start MySQL
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Create Drupal install path
  file:
    path: "{{ drupal_site_path }}"
    state: directory

- name: Fix permissions
  file:
    path: "{{ drupal_site_path }}"
    owner: wilfred
    mode: 0777
    state: directory
    recurse: yes

- name: Create Drupal Recommended project
  shell: /usr/local/bin/composer create-project drupal/recommended-project drupal
  become_user: wilfred
  args:
    chdir: "{{ drupal_site_path }}"

- name: Full permissions for Drupal project
  file:
    path: "{{ drupal_site_path }}/drupal"
    owner: wilfred
    mode: 0777
    state: directory
    recurse: yes

- name: Install Drush and update
  shell: |
    /usr/local/bin/composer require --dev drush/drush --no-interaction
    /usr/local/bin/composer update --no-interaction
  become_user: wilfred
  args:
    chdir: "{{ drupal_site_path }}/drupal"